In [32]:
import os
os.chdir(r'H:\平台资源配套\4 Python数据分析与应用\01-数据和代码\第2章\01-任务程序')

In [10]:
import numpy as np
a = np.array([[1, 2, 3], [1, 2, 4]], dtype=np.float32)
a.size
a.shape
a.ndim
a.dtype

dtype('float32')

In [11]:
a.reshape(3, 2)

array([[1., 2.],
       [3., 1.],
       [2., 4.]], dtype=float32)

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(10)
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
np.logspace(0, 10, 10, endpoint=False, base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [19]:
2**np.linspace(0, 10, 10, endpoint=False)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [21]:
np.zeros(2)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.ones(2)
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.diag([1, 2])

array([[1, 0],
       [0, 2]])

In [31]:
a = np.array([1, 2, 3], dtype=np.int8)
a.dtype

dtype('int8')

In [33]:
b = np.int32(a)
b.dtype

dtype('int32')

In [35]:
np.random.random(size=(2, 3))

array([[0.04935258, 0.78870581, 0.71236402],
       [0.40832478, 0.44271514, 0.85875113]])

In [37]:
np.random.rand(2, 3, 2)

array([[[0.67638841, 0.06254317],
        [0.00534974, 0.62611344],
        [0.48640407, 0.84134312]],

       [[0.9041065 , 0.81728973],
        [0.61529276, 0.71713412],
        [0.76829216, 0.88545205]]])

In [38]:
np.random.randn(2, 3, 2)

array([[[ 0.63844709, -0.76171006],
        [ 0.28394952,  0.48926086],
        [ 0.95800496,  0.55339545]],

       [[-0.27053916, -1.49729261],
        [-0.27266521,  0.96275085],
        [ 0.7302607 , -0.37779586]]])

In [39]:
np.random.randint(0, 10, size=(2, 3))

array([[4, 8, 7],
       [7, 0, 8]])

In [50]:
a = np.arange(10)
a[2]
a[2:]
a[:5]
a[1:-1:2]

array([1, 3, 5, 7])

In [46]:
b = np.random.randint(0, 10, size=(2, 3))
b[1, :]

array([7, 9, 5])

In [47]:
b

array([[0, 2, 9],
       [7, 9, 5]])

In [48]:
b[:, 0]

array([0, 7])

In [51]:
b[:, ::2]

array([[0, 9],
       [7, 5]])

In [53]:
b.ravel()

array([0, 2, 9, 7, 9, 5])

In [54]:
b.flatten()

array([0, 2, 9, 7, 9, 5])

In [55]:
b.flatten(order='F')

array([0, 7, 2, 9, 9, 5])

In [59]:
a = np.arange(10).reshape(2, 5)
b = np.linspace(0, 1, endpoint=False, num=10).reshape(2, 5)

In [58]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
b

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [63]:
np.vstack((a, b))
np.concatenate((a, b), axis=0)

array([[0. , 1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. , 9. ],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [65]:
np.hstack((a, b))
np.concatenate((a, b), axis=1)

array([[0. , 1. , 2. , 3. , 4. , 0. , 0.1, 0.2, 0.3, 0.4],
       [5. , 6. , 7. , 8. , 9. , 0.5, 0.6, 0.7, 0.8, 0.9]])

In [2]:
import numpy as np
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
a = np.mat([[1, 2], [3, 4]])

In [6]:
b = np.matrix([[11, 21], [31, 41]])

In [8]:
np.bmat('a b; b a')

matrix([[ 1,  2, 11, 21],
        [ 3,  4, 31, 41],
        [11, 21,  1,  2],
        [31, 41,  3,  4]])

In [14]:
a = [[1, 2], [3, 4]]
b = [[1, 1], [1, 1]]
np.array(a) * np.array(b)
np.array(a).dot(np.array(b))

array([[3, 3],
       [7, 7]])

In [11]:
np.matrix(a) * np.matrix(b)

matrix([[3, 3],
        [7, 7]])

In [13]:
print(np.matrix(a))
print(np.matrix(b))

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [19]:
np.matrix(a).T

matrix([[1, 3],
        [2, 4]])

In [22]:
[[j**2 for j in i] for i in a]

[[1, 4], [9, 16]]

In [23]:
np.array(a) ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [31]:
a = [[0]*3, [1]*3, [2]*3, [3]*3]
np.array(a) + np.array([1, 2, 3])
np.array(a) + np.array([[1], [2], [3], [4]])

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [54]:
import numpy as np
a = np.random.random((3, 3))
a

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [55]:
np.save('./tmp/tmp.npy', a)
# np.save()

In [56]:
b = np.random.randn(2, 2)
b

array([[-0.96641709, -0.22068483],
       [ 0.62706947, -0.55555186]])

In [57]:
np.savez('./tmp/tmp2.npz', a, b)
# np.savez()

In [58]:
np.load('./tmp/tmp.npy')

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [60]:
d = np.load('./tmp/tmp2.npz')

In [61]:
d['arr_0']

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [62]:
d['arr_1']

array([[-0.96641709, -0.22068483],
       [ 0.62706947, -0.55555186]])

In [63]:
d.files

['arr_0', 'arr_1']

In [64]:
np.savetxt('./tmp/tmp3.txt', a)

In [65]:
np.loadtxt('./tmp/tmp3.txt')

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [66]:
np.genfromtxt('./tmp/tmp3.txt')

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [67]:
a

array([[0.86705753, 0.47270344, 0.46960053],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [69]:
a.sort(axis=1)

In [70]:
a

array([[0.46960053, 0.47270344, 0.86705753],
       [0.24891569, 0.52897057, 0.98737962],
       [0.51857887, 0.58543909, 0.61704753]])

In [72]:
c = np.array([92, 1, 32])
c.sort()
c

array([ 1, 32, 92])

In [74]:
c = np.array([92, 1, 32])
c.argsort()

array([1, 2, 0], dtype=int64)

In [75]:
np.repeat(c, 2)

array([92, 92,  1,  1, 32, 32])

In [76]:
np.tile(c, 2)

array([92,  1, 32, 92,  1, 32])

In [77]:
np.unique(np.tile(c, 2))

array([ 1, 32, 92])

读取iris数据集中的花萼长度数据（已保存为csv格式），并对其进行排序、去重，并求出和、累积和、均值、标准差、方差、最小值、最大值


In [79]:
data = np.loadtxt('./data/iris_sepal_length.csv')

In [80]:
data.sort()

In [85]:
data = np.unique(data)

In [86]:
np.sum(data)

210.39999999999998

In [87]:
np.cumsum(data)

array([  4.3,   8.7,  13.2,  17.8,  22.5,  27.3,  32.2,  37.2,  42.3,
        47.5,  52.8,  58.2,  63.7,  69.3,  75. ,  80.8,  86.7,  92.7,
        98.8, 105. , 111.3, 117.7, 124.2, 130.8, 137.5, 144.3, 151.2,
       158.2, 165.3, 172.5, 179.8, 187.2, 194.8, 202.5, 210.4])

In [88]:
print(np.mean(data))# 均值、
print(np.std(data))# 标准差、
print(np.var(data))# 方差、
print(np.min(data))# 最小值、
print(np.max(data))# 最大值

6.011428571428571
1.0289443768310533
1.0587265306122449
4.3
7.9
